name: Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  windowsAmd64Build:
    name: Build Windows amd64 Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
      - name: Building Windows amd64 Version
        run: |
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o WireProxy_amd64.exe -v ./cmd/wireproxy
          mkdir release_windows_amd64
          mv WireProxy_amd64.exe wireproxy.exe
          cp wireproxy.exe release_windows_amd64/wireproxy.exe
      - name: Upload Windows amd64 Version
        uses: actions/upload-artifact@v1
        with:
          name: WireProxy_windows_amd64
          path: release_windows_amd64
  linuxAmd64Build:
    name: Build Linux amd64 Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
      - name: Building Linux amd64 Version
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o WireProxy_amd64 -v ./cmd/wireproxy
          mkdir release_linux_amd64
          mv WireProxy_amd64 wireproxy
          cp wireproxy release_linux_amd64/wireproxy
      - name: Upload Linux amd64 Version
        uses: actions/upload-artifact@v1
        with:
          name: WireProxy_linux_amd64
          path: release_linux_amd64

          
